name: Starter Template App New1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
      - main
    paths:
      - '.github/workflows/starter_template_app_new1_verify_and_test.yaml'
      - '**'

  push:
    branches:
      - master
      - main
    paths:
      - '.github/workflows/**'
      - '**'


jobs:
  verify_and_test:
    name: Verify and Test
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1.12.0
    with:
      working_directory: .
      min_coverage: 100
      flutter_channel: stable
      flutter_version: 3.7.6